version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.12.3

    working_directory: ~/repo

    steps:
      - checkout
      
      - deploy:
          name: Deploy Master to Firebase
          command: |
            ./node_modules/.bin/firebase use cat-gif-tv --token=$FIREBASE_DEPLOY_TOKEN
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
            fi
